services:
  php:
    image: php:8.2-fpm
    container_name: api_php
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /var/www/html
    volumes:
      - ..:/var/www/html
      - ./logs/php:/var/log/php
    environment:
      - USER_ID=${UID}
      - GROUP_ID=${GID}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: api_nginx
    ports:
      - "${HTTP_PORT}:80"
    volumes:
      - ..:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: api_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: api_database
      MYSQL_USER: api_user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql


  mailhog:
    image: mailhog/mailhog
    container_name: api_mailhog
    ports:
      - "${MAILHOG_SMTP_PORT}:1025"
      - "${MAILHOG_UI_PORT}:8025"

volumes:
  mysql_data:
